# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import venues.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
        ('products', '0001_initial'),
        ('locations', '0001_initial'),
        ('tags', '0001_initial'),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.Color')),
            ],
            options={
                'verbose_name_plural': 'Venue Attributes',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.FileField(blank=True, default=None, null=True, upload_to=venues.models.upload_logo_image)),
            ],
            options={
                'verbose_name_plural': 'Venue Brand',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(default=None, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Venue Types',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('small_description', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=venues.models.upload_venue_image)),
                ('products_count', models.IntegerField(blank=True, null=True)),
                ('star_rating', models.IntegerField(blank=True, null=True)),
                ('member_rating', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('height', models.IntegerField(default=120)),
                ('controller_style', models.CharField(blank=True, choices=[(b'1', b'ProwlistControllerStyleDefault'), (b'2', b'ProwlistControllerStyleLight')], default=None, max_length=32, null=True)),
                ('address', models.CharField(default=None, max_length=200, null=True)),
                ('logo_file', models.ImageField(blank=True, default=None, null=True, upload_to=venues.models.upload_venue_image)),
                ('attributes', models.ManyToManyField(blank=True, to='venues.Attribute')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.Brand')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
                ('products', models.ManyToManyField(blank=True, to='products.Product')),
                ('sensors', models.ManyToManyField(blank=True, to='sensors.Sensor')),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
                ('tint', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='themes.Color')),
                ('types', models.ManyToManyField(blank=True, to='venues.Type')),
            ],
            options={
                'verbose_name_plural': 'Venues',
            },
        ),
    ]
