# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 02:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0002_venue_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
