# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uuid', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('serial', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=17, default=None, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=17, default=None, max_digits=20, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'Sensors (Proximity detectors)',
            },
        ),
        migrations.CreateModel(
            name='SensorLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('validated_email_date', models.DateTimeField(blank=True, null=True)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.Sensor')),
            ],
            options={
                'verbose_name_plural': 'Sensor Logs',
            },
        ),
    ]
